name: Terraform Release Pipeline

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  terraform-deploy:
    name: Deploy with Terraform
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set AWS Credentials from GitHub Secrets
      - name: Set AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}" >> $GITHUB_ENV

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      # Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./iac

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./iac

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: ./iac

      # Optional: Upload Terraform state
      - name: Upload Terraform State
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: iac/terraform.tfstate
